sylius_twig_hooks:
    hooks:
        'sylius_admin.order.history.content.sections':
            monsieurbiz_multichannel_admin_order_history_content:
                template: '@MonsieurBizSyliusOrderHistoryPlugin/admin/order/history/content/sections/timelines.html.twig'
                priority: 0

        'sylius_admin.order.history.content.sections.timelines':
            billing_address:
                component: sylius_admin:monsieurbiz_order_history:order_history
                props:
                    orderId: '@=_context.resource.getId()'
                    header: 'mbiz_order_history.ui.order_timeline'
                    template: '@MonsieurBizSyliusOrderHistoryPlugin/admin/order/history/content/sections/timelines/order_history.html.twig'
                priority: 100

        'sylius_admin.order.history.content.sections.timelines.common.side':
            side_content:
                template: '@MonsieurBizSyliusOrderHistoryPlugin/admin/order/history/content/sections/timelines/order_history/side.html.twig'
                priority: 0
        'sylius_admin.order.history.content.sections.timelines.common.side.label':
            datetime:
                template: '@MonsieurBizSyliusOrderHistoryPlugin/admin/order/history/content/sections/timelines/order_history/side/label/default.html.twig'
                priority: 0
        'sylius_admin.order.history.content.sections.timelines.checkout.side.label':
            datetime:
                template: '@MonsieurBizSyliusOrderHistoryPlugin/admin/order/history/content/sections/timelines/order_history/side/label/checkout.html.twig'
                priority: 0
        'sylius_admin.order.history.content.sections.timelines.order.side.label':
            datetime:
                template: '@MonsieurBizSyliusOrderHistoryPlugin/admin/order/history/content/sections/timelines/order_history/side/label/order.html.twig'
                priority: 0
        'sylius_admin.order.history.content.sections.timelines.payment.side.label':
            datetime:
                template: '@MonsieurBizSyliusOrderHistoryPlugin/admin/order/history/content/sections/timelines/order_history/side/label/payment.html.twig'
                priority: 0
        'sylius_admin.order.history.content.sections.timelines.shipment.side.label':
            datetime:
                template: '@MonsieurBizSyliusOrderHistoryPlugin/admin/order/history/content/sections/timelines/order_history/side/label/shipment.html.twig'
                priority: 0
        'sylius_admin.order.history.content.sections.timelines.common.side.datetime':
            datetime:
                template: '@MonsieurBizSyliusOrderHistoryPlugin/admin/order/history/content/sections/timelines/order_history/side/datetime.html.twig'
                priority: 0

        'sylius_admin.order.history.content.sections.timelines.common.main':
            main_content:
                template: '@MonsieurBizSyliusOrderHistoryPlugin/admin/order/history/content/sections/timelines/order_history/main.html.twig'
                priority: 0

        'sylius_admin.order.history.content.sections.timelines.common.main.identity':
            identity:
                template: '@MonsieurBizSyliusOrderHistoryPlugin/admin/order/history/content/sections/timelines/order_history/main/identity.html.twig'
                priority: 0

        'sylius_admin.order.history.content.sections.timelines.common.main.content':
            content:
                template: '@MonsieurBizSyliusOrderHistoryPlugin/admin/order/history/content/sections/timelines/order_history/main/content.html.twig'
                priority: 0

        'sylius_admin.order.history.content.sections.timelines.common.main.statuses':
            content:
                template: '@MonsieurBizSyliusOrderHistoryPlugin/admin/order/history/content/sections/timelines/order_history/main/statuses.html.twig'
                priority: 0

        'sylius_admin.order.history.content.sections.addresses.billing_address.details':
            data:
                template: '@MonsieurBizSyliusOrderHistoryPlugin/admin/order/history/address/data.html.twig'
        'sylius_admin.order.history.content.sections.addresses.shipping_address.details':
            data:
                template: '@MonsieurBizSyliusOrderHistoryPlugin/admin/order/history/address/data.html.twig'

        'sylius_admin.order.history.content.sections.addresses.billing_address.details.data':
            phone_number:
                template: '@MonsieurBizSyliusOrderHistoryPlugin/admin/order/history/address/optional_field.html.twig'
                configuration: { field: phoneNumber, label: 'sylius.ui.phone_number' }
            company:
                template: '@MonsieurBizSyliusOrderHistoryPlugin/admin/order/history/address/optional_field.html.twig'
                configuration: { field: company, label: 'sylius.ui.company' }
            province_code:
                template: '@MonsieurBizSyliusOrderHistoryPlugin/admin/order/history/address/optional_field.html.twig'
                configuration: { field: provinceCode, label: 'sylius.ui.province_code' }
            province_name:
                template: '@MonsieurBizSyliusOrderHistoryPlugin/admin/order/history/address/optional_field.html.twig'
                configuration: { field: provinceName, label: 'sylius.ui.province_name' }

        'sylius_admin.order.history.content.sections.addresses.shipping_address.details.data':
            phone_number:
                template: '@MonsieurBizSyliusOrderHistoryPlugin/admin/order/history/address/optional_field.html.twig'
                configuration: { field: phoneNumber, label: 'sylius.ui.phone_number' }
            company:
                template: '@MonsieurBizSyliusOrderHistoryPlugin/admin/order/history/address/optional_field.html.twig'
                configuration: { field: company, label: 'sylius.ui.company' }
            province_code:
                template: '@MonsieurBizSyliusOrderHistoryPlugin/admin/order/history/address/optional_field.html.twig'
                configuration: { field: provinceCode, label: 'sylius.ui.province_code' }
            province_name:
                template: '@MonsieurBizSyliusOrderHistoryPlugin/admin/order/history/address/optional_field.html.twig'
                configuration: { field: provinceName, label: 'sylius.ui.province_name' }
